fail_fast: true
default_language_version:
  golang: "1.22.2"
repos:
  - repo: local
    hooks:
      - id: requirements-installed
        name: check for required tooling
        language: system
        entry: ./scripts/check-prereq.sh
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - "json"
      - id: end-of-file-fixer
        exclude_types:
          - "json"
      - id: check-added-large-files
  - repo: "https://github.com/google/yamlfmt"
    rev: v0.13.0
    hooks:
      - id: yamlfmt
        name: yamlfmt
        description: yamlfmt to format yaml files
        entry: yamlfmt -conf ./.yamlfmt.yaml
        language: system
        pass_filenames: true
        types: [yaml]

